config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items do
    get :upvote,    on: :member
    get :expensive, on: :collection
  end
  #get ':controller(/:action(/:id))(.:format)'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many      :positions
  belongs_to    :user, optional: true
  has_many      :items, through: :positions


end

app/models/item.rb
class Item < ApplicationRecord

    validates :price, numericality: { greater_than: 0, allow_nil: true }
    validates :name, :description, presence: true
    validates :name, presence: true


    has_many  :positions
    has_many  :carts, through: :positions



end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user

end

app/models/position.rb
class Position < ApplicationRecord

  belongs_to :item
  belongs_to :cart

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_one  :cart
  has_many :orders

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  private

  def render_403
    render file: 'public/403.html', status: 403
  end

  def render_404
    render file: 'public/404.html', status: 404
  end

  def check_if_admin
    render_403 unless params[:admin]
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :find_item, only: [:show, :edit, :update, :destroy, :upvote]
  before_filter :check_if_admin, only: [:new, :edit, :update, :destroy, :create]

  def index
    @items = Item.all
  end

  def expensive
    @items = Item.where('price > 1000')
    render 'index'
  end

  def show
   unless @item
     render text: "Page not found", status: 404
     end
  end

  # /items/new GET
  def new
    @item = Item.new
  end

  # /items/1/edit GET
  def edit
  end

  # /items POST
  def create
    @item = Item.create(item_params)
    if @item.errors.empty?
      redirect_to item_path(@item)
    else
      render "new"
    end
  end

  # /items/1 PUT
  def update
    @item.update_attributes(item_params)
    if @item.errors.empty?
      redirect_to item_path(@item)
    else
      render "edit"
    end
  end
  # /items/1 DELETE
  def destroy
    @item.destroy
    redirect_to action: 'index'
  end

  def upvote
    @item.increment!(:votes_count)
    redirect_to action: :index
  end

  private

  def item_params
    params.require(:item).permit(:price, :name, :real, :weight, :description)
  end

  def find_item
    @item = Item.where(id: params[:id]).first
    render_404 unless @item
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Edit item</h1>

<%= form_for @item do |f| %>

    <p>Цена: <br/><%= f.text_field :price %></p>
    <p>Название: <br/><%= f.text_field :name %></p>
    <p>Описание: <br/><%= f.text_field :description %></p>
    <p>Вес: <br/><%= f.text_field :weight %></p>

    <p><%= f.submit "Сохранить товар" %></p>

<% end %>

app/views/items/index.html.erb
<h1>Items</h1>

<% if @items.empty? %>
  <b>No items in store</b>
<% else %>
<table>
  <tr>
    <th>ited id</th>
    <th>Name</th>
    <th>Price</th>
    <th></th>
    <th></th>
  </tr>

  <% @items.each do |i| %>

    <tr>
      <td><%= i.id %></td>
      <td><%= link_to i.name, item_path(i) %></td>
      <td><%= i.price %></td>
      <td><%=link_to 'Удалить', item_path(i), method: :delete, data: { confirm: 'Точно удалить?'} %></td>
      <td>Рейтинг: <%= i.votes_count %>, <%= link_to '+', upvote_item_path(i) %></td>
    </tr>

<% end %>

</table>
<% end %>

app/views/items/new.html.erb
<h1>Create new item</h1>

<%= form_for @item do |f| %>

    <p>Цена: <br/><%= f.text_field :price %></p>
    <p>Название: <br/><%= f.text_field :name %></p>
    <p>Описание: <br/><%= f.text_field :description %></p>
    <p>Вес: <br/><%= f.text_field :weight %></p>

    <p><%= f.submit "Создать товар" %></p>

<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<ul>
  <li><%= @item.price %> руб.</li>
  <li><%= @item.description %></li>
  <li>Вес: <%= @item.weight %>кг.</li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>